const PAGE1 = {
  LOADING: 'PAGE_1_LOADING',
  FETCH_SUCCESS: 'PAGE_1_FETCH_SUCCESS',
  FETCH_FAILED: 'PAGE_1_FETCH_FAILED'
};

const POST_DETAIL = {
  LOADING: 'POST_DETAIL_LOADING',
  FETCH_SUCCESS: 'POST_DETAIL_FETCH_SUCCESS',
  FETCH_FAILED: 'POST_DETAIL_FETCH_FAILED'
}

export { PAGE1 , POST_DETAIL };
